from __future__ import annotations

KERALA_ABBREVIATIONS: dict[str, str] = {
    "sc": "school spiral closed",
    "mr": "margin ruled",
    "dl": "double line",
    "sl": "single line",
    "4l": "four line",
    "m.sq": "maths square graph",
    "ur": "unruled",
    "ftgr": "fenugreek collection footwear",
    "pdr": "powder",
    "pch": "pouch",
    "btl": "bottle",
    "pet": "pet bottle",
    "nos": "numbers units",
    "ss": "stainless steel",
    "kc": "kitchen container",
    "db": "design black",
    "dg": "dark grey",
    "brn": "brown",
    "tab": "tan brown",
    "lad": "ladies footwear",
    "lady": "ladies footwear",
    "ladies": "ladies footwear",
    "gent": "gents footwear",
    "gents": "gents footwear",
    "inf": "infant footwear",
    "kids": "children footwear",
    "esl": "smooth line pen",
    "btf": "big bottle",
    "pck": "pack",
    "pkt": "packet",
    "asstd": "assorted",
    "asst": "assorted",
    "btrm": "bathroom",
    "bathrm": "bathroom",
    "clnr": "cleaner",
    "disinftnt": "disinfectant",
    "florl": "floral fragrance",
    "vanlla": "vanilla",
    "vaniila": "vanilla",
    "vannila": "vanilla",
    "jasmne": "jasmine",
    "strbry": "strawberry",
    "cashw": "cashew",
    "cookis": "cookies",
    "cooki": "cookie",
    "digestve": "digestive",
    "iodised": "iodized",
    "milkrunch": "milk crunch biscuit",
    "nc": "nice biscuit",
    "safai": "cleaning shine steel",
    "bigblister": "big blister pack",
    "tr": "kitchen treasure",
    "puja": "puja lamp oil sesame",
    "pooja": "pooja lamp oil sesame",
    "nadan": "traditional local",
    "vadi": "variety grade",
    "dubar": "dubar grade rice",
    "steam": "steam made",
    "puttupodi": "rice puttu flour",
    "aval": "beaten rice poha",
    "matta": "matta red rice",
    "kappa": "tapioca cassava",
    "kozhuva": "anchovy fish",
    "palada": "ada rice payasam",
    # Common invoice shorthand used in Kerala trade
    "choc": "chocolate",
    "choco": "chocolate",
    "bisckt": "biscuit",
    "bisct": "biscuit",
    "butr": "butter",
    "margn": "margarine",
    "atta": "wheat flour atta",
    "maida": "refined wheat flour maida",
    "rawa": "semolina rawa sooji",
    "sooji": "semolina rawa sooji",
    "rava": "semolina rava sooji",
    "dalda": "vanaspati hydrogenated vegetable oil",
    "ghee": "clarified butter ghee dairy",
    "coconut oil": "coconut edible oil",
    "VCO": "virgin coconut oil",
    "vco": "virgin coconut oil",
    "cpra": "copra dried coconut kernel",
    "keri": "raw mango pickle",
    "manga": "mango raw fresh",
    "chena": "yam elephant foot",
    "chembu": "taro colocasia root",
    "njandu": "crab seafood crustacean",
    "chemmeen": "prawn shrimp seafood",
    "karimeen": "pearl spot fish kayal",
    "vaval": "pomfret fish",
    "ayala": "mackerel fish",
    "mathi": "sardine fish",
    "nellikka": "amla gooseberry",
    "muringakka": "drumstick moringa pods",
    "pavakka": "bitter gourd karela",
    "cheera": "amaranth spinach red",
    "muringayila": "moringa leaves drumstick leaf",
    "thean": "honey bee product",
    "coir": "coir coconut fibre rope mat",
    "aluva": "alwa sweet halwa",
    "kalathappam": "rice cake steam traditional",
    "unniyappam": "rice ball sweet appam",
    "ada": "rice ada payasam ingredient",
    "palpayasam": "milk payasam kheer rice",
    "chakka": "jackfruit tropical fruit",
    "chakkakuru": "jackfruit seed",
    "vazhakka": "raw banana plantain cooking",
    "ethakka": "nendran banana plantain",
    "cherupayar": "green gram moong dal",
    "vanpayar": "cowpea red gram lobiya",
    "uzhunnu": "urad dal black gram",
    "kadala mavu": "chickpea flour besan gram",
    "kadala": "black chickpea chana",
    "kanji": "rice gruel porridge",
    "parotta": "layered flatbread maida",
    "pathiri": "rice bread flat rice roti",
    "porichathu": "fried fish fry",
    "mappas": "coconut fish curry stew",
    "sambar": "lentil vegetable curry",
    "rasam": "pepper soup thin curry",
    "thoran": "dry stir fry vegetable",
    "olan": "ash gourd coconut curry",
    "avial": "mixed vegetable coconut curry",
    "pachadi": "yogurt vegetable side dish",
    "kichadi": "yogurt cucumber raita",
    "sadya": "traditional meal banana leaf",
    "kaalan": "yam buttermilk gravy",
    "erissery": "pumpkin coconut curry",
    "mezhukupuratti": "stir fry vegetable oil",
    "uppumanga": "salted raw mango brine pickle",
    "naranga": "lime lemon citrus",
    "kudampuli": "gamboge kokum tamarind",
    "tomato": "tomato fresh vegetable",
    "mulaku": "chilli pepper dry",
    "kurumulaku": "black pepper whole",
    "jeerakam": "cumin seeds jeera",
    "dhania": "coriander seeds powder",
    "manjal": "turmeric powder haldi",
    "inchi": "ginger fresh dry",
    "veluthulluli": "garlic whole clove",
    "ulli": "onion shallot small",
    "savola": "savola brand onion shallots",
    # Stationery
    "NB": "notebook",
    "SNB": "short notebook",
    "LNB": "long notebook",
    "DL": "double line ruled",
    "SL": "single line ruled",
    "SQ": "square graph notebook",
    "GR": "graph ruled",
    "FCP": "foolscap paper",
    # Footwear
    "hawai": "hawai chappal slipper rubber footwear",
    "eva": "eva foam footwear sole",
    "pu": "polyurethane footwear sole",
    "PU": "polyurethane footwear sole",
    "TPR": "thermoplastic rubber sole footwear",
    "tpr": "thermoplastic rubber sole footwear",
    "MCR": "micro cellular rubber footwear",
    "mcr": "micro cellular rubber footwear",
    # Cleaning / FMCG
    "detgt": "detergent",
    "detgnt": "detergent",
    "phenyl": "phenyl floor cleaner disinfectant",
    "lizol": "floor cleaner disinfectant",
    "HIT": "insecticide spray",
    "hit": "insecticide mosquito spray",
    "good knight": "mosquito repellent coil mat",
    "mortein": "insecticide mosquito repellent",
    "allout": "mosquito repellent liquid",
    # Dairy
    "MILMA": "dairy milk cooperative kerala",
    "milma": "dairy milk cooperative kerala",
    "paal": "milk dairy liquid",
    "toned milk": "toned milk dairy low fat",
    "full cream": "full cream milk dairy",
    "skimmed": "skimmed milk powder",
    # Tobacco
    "beedi": "beedi bidi tobacco rolled",
    "gutka": "gutka chewing tobacco",
    "pan masala": "pan masala betel nut preparation",
    "zarda": "zarda chewing tobacco scented",
}

KERALA_SYNONYMS: dict[str, list[str]] = {
    "puttu": ["rice flour", "steamed cake", "puttupodi"],
    "puttupodi": ["rice flour", "puttu flour", "puttu"],
    "aval": ["beaten rice", "poha", "flattened rice", "rice flakes"],
    "appam": ["rice batter", "hoppers", "appam flour", "idiappam"],
    "idiyappam": ["string hoppers", "rice vermicelli", "appam"],
    "matta": ["red rice", "rosematta", "kerala rice"],
    "kappa": ["tapioca", "cassava", "yuca"],
    "tapioca": ["kappa", "cassava", "tapioca chips"],
    "kozhuva": ["anchovy", "fish", "sardine", "dried fish"],
    "kallumakkaya": ["mussels", "shellfish", "shellfish seafood"],
    "payasam": ["kheer", "dessert mix", "palada"],
    "palada": ["payasam", "ada", "rice kheer"],
    "puja oil": ["lamp oil", "sesame oil", "pooja oil", "gingelly"],
    "pooja oil": ["lamp oil", "sesame oil", "puja oil", "gingelly"],
    "gingelly": ["sesame oil", "til oil", "sesame", "ellu"],
    "sambar podi": ["sambar masala", "sambar powder", "spice mix"],
    "rasam podi": ["rasam powder", "pepper soup spice", "spice mix"],
    "nadan": ["traditional", "country style", "local", "homemade style"],
    "dubar": ["medium grain rice", "rice variety", "basmati grade"],
    "vkc": ["footwear", "sandal", "slipper", "hawai", "chappal"],
    "milma": ["dairy", "cooperative milk", "kerala milk", "ghee"],
    "eastern": ["spice", "masala powder", "turmeric", "coriander"],
    "brahmins": ["masala", "spice mix", "paste", "coconut milk"],
    "kitchen tr": ["masala", "spice blend", "kitchen treasure"],
    "pavithram": ["sesame oil", "gingelly", "cooking oil"],
    "idhayam": ["sesame oil", "gingelly oil", "til oil"],
    "pathimugham": ["sarsaparilla", "herbal drink", "medicinal herb"],
    "unniyappam": ["sweet appam", "rice ball sweet", "traditional sweet"],
}

KERALA_DOMAIN_PREFIXES: dict[str, list[str]] = {
    "puttupodi": ["11"],
    "puttu": ["11"],
    "appam": ["11"],
    "idiyappam": ["11"],
    "aval": ["19"],
    "matta": ["10"],
    "tapioca": ["20", "07"],
    "kappa": ["20", "07"],
    "kozhuva": ["03"],
    "kallumakkaya": ["03"],
    "njandu": ["03"],
    "karimeen": ["03"],
    "brahmins": ["09", "20"],
    "eastern": ["09"],
    "kitchen tr": ["09"],
    "aachi": ["09"],
    "pavithram": ["15"],
    "idhayam": ["15"],
    "gingelly": ["15"],
    "puja oil": ["15"],
    "pooja oil": ["15"],
    "milma": ["04"],
    "pathimugham": ["12"],
    "unniyappam": ["19"],
    "payasam": ["19"],
    "palada": ["19"],
}

KERALA_CATEGORY_RULES: list[dict[str, list[str]]] = [
    {"keywords": ["puttupodi", "puttu", "puttu podi", "steam made"], "chapters": ["11"]},
    {"keywords": ["appam podi", "appam flour", "idiyappam", "idiappam"], "chapters": ["11"]},
    {"keywords": ["aval", "beaten rice", "poha", "flattened rice"], "chapters": ["19"]},
    {"keywords": ["matta rice", "matta broken", "rosematta", "matta vadi"], "chapters": ["10"]},
    {"keywords": ["tapioca chips", "kappa chips", "cassava chips"], "chapters": ["20"]},
    {"keywords": ["tapioca", "kappa", "cassava root"], "chapters": ["07"]},
    {"keywords": ["kozhuva", "kallumakkaya", "njandu", "karimeen", "anchovy"], "chapters": ["03"]},
    {"keywords": ["puja oil", "pooja oil", "lamp oil", "thiri oil", "puja thiri"], "chapters": ["15"]},
    {"keywords": ["unniyappam", "nadan unniyappam", "rice ball sweet"], "chapters": ["19"]},
    {"keywords": ["payasam mix", "palada mix", "kheer mix"], "chapters": ["19"]},
    {"keywords": ["pathimugham", "sarsaparilla"], "chapters": ["12"]},
]

KERALA_BRANDS: dict[str, dict[str, str]] = {
    "EASTERN": {"category": "spice", "chapter": "09"},
    "NIRAPARA": {"category": "flour rice puttu", "chapter": "11"},
    "BRAHMINS": {"category": "spice masala", "chapter": "09"},
    "KITCHEN TR": {"category": "spice masala", "chapter": "09"},
    "PAVITHRAM": {"category": "oil gingelly sesame", "chapter": "15"},
    "IDHAYAM": {"category": "oil gingelly sesame", "chapter": "15"},
    "MILMA": {"category": "dairy milk ghee", "chapter": "04"},
    "DOUBLE HORSE": {"category": "flour rice puttu", "chapter": "11"},
    "ELITE": {"category": "rice flour puttu", "chapter": "11"},
    "AJMI": {"category": "rice flour puttu", "chapter": "11"},
    "BODHINI": {"category": "flour appam", "chapter": "11"},
    "NOLTA": {"category": "kitchen tools scissors", "chapter": "82"},
    "ELKO": {"category": "pen stationery", "chapter": "96"},
    "VKC": {"category": "footwear sandal", "chapter": "64"},
}

KERALA_BRAND_WORDS: set[str] = {
    "vkc",
    "cb",
    "kitchen",
    "treasure",
    "milma",
    "ajmi",
    "bodhini",
    "elite",
}

# Curated GST-critical overrides; merged below with corpus-derived keys (curated wins).
CURATED_KERALA_ALIAS_MAP: dict[str, dict] = {
    "PUTTU": {
        "search_terms": ["rice puttu flour", "steamed puttu"],
        "hsn_code": "11023000",
        "gst_rate": 5,
        "description": "Rice puttu flour",
        "confidence": 0.86,
        "category": "kerala_food",
    },
    "PUTTUPODI": {
        "search_terms": ["rice puttu flour", "steamed puttu", "puttu podi"],
        "hsn_code": "11023000",
        "gst_rate": 5,
        "description": "Rice puttu flour",
        "confidence": 0.9,
        "category": "kerala_food",
    },
    "APPAM PODI": {
        "search_terms": ["appam batter", "rice flour appam"],
        "hsn_code": "11029090",
        "gst_rate": 5,
        "description": "Appam flour",
        "confidence": 0.88,
        "category": "kerala_food",
    },
    "APPAM FLOUR": {
        "search_terms": ["appam batter", "rice flour appam"],
        "hsn_code": "11029090",
        "gst_rate": 5,
        "description": "Appam flour",
        "confidence": 0.88,
        "category": "kerala_food",
    },
    "IDIYAPPAM": {
        "search_terms": ["string hoppers", "rice vermicelli flour"],
        "hsn_code": "11029090",
        "gst_rate": 5,
        "description": "Idiyappam flour",
        "confidence": 0.88,
        "category": "kerala_food",
    },
    "IDIAPPAM": {
        "search_terms": ["string hoppers", "rice vermicelli flour"],
        "hsn_code": "11029090",
        "gst_rate": 5,
        "description": "Idiyappam flour",
        "confidence": 0.88,
        "category": "kerala_food",
    },
    "AVAL": {
        "search_terms": ["beaten rice", "flattened rice", "poha"],
        "hsn_code": "19041020",
        "gst_rate": 5,
        "description": "Beaten rice",
        "confidence": 0.87,
        "category": "kerala_food",
    },
    "AVAL WHITE": {
        "search_terms": ["beaten rice", "flattened rice", "poha"],
        "hsn_code": "19041020",
        "gst_rate": 5,
        "description": "White aval beaten rice",
        "confidence": 0.89,
        "category": "kerala_food",
    },
    "MATTA RICE": {
        "search_terms": ["kerala red rice", "rosematta", "matta broken"],
        "hsn_code": "10063090",
        "gst_rate": 5,
        "description": "Kerala matta rice",
        "confidence": 0.88,
        "category": "kerala_food",
    },
    "MATTA VADI": {
        "search_terms": ["kerala red rice", "rosematta", "matta broken"],
        "hsn_code": "10063090",
        "gst_rate": 5,
        "description": "Kerala matta rice variety",
        "confidence": 0.87,
        "category": "kerala_food",
    },
    "PALADA": {
        "search_terms": ["ada payasam mix", "rice flakes", "palada payasam"],
        "hsn_code": "19019090",
        "gst_rate": 18,
        "description": "Palada payasam mix",
        "confidence": 0.88,
        "category": "kerala_food",
    },
    "PALADA MIX": {
        "search_terms": ["ada payasam mix", "rice flakes", "palada payasam"],
        "hsn_code": "19019090",
        "gst_rate": 18,
        "description": "Palada mix",
        "confidence": 0.89,
        "category": "kerala_food",
    },
    "PAYASAM MIX": {
        "search_terms": ["kheer mix", "payasam powder", "palada mix"],
        "hsn_code": "19019090",
        "gst_rate": 18,
        "description": "Payasam mix",
        "confidence": 0.88,
        "category": "kerala_food",
    },
    "UNNIYAPPAM": {
        "search_terms": ["sweet rice ball", "appam snack"],
        "hsn_code": "19059090",
        "gst_rate": 18,
        "description": "Unniyappam snack",
        "confidence": 0.84,
        "category": "kerala_food",
    },
    "NADAN UNNIYAPPAM": {
        "search_terms": ["sweet rice ball", "appam snack", "traditional sweet"],
        "hsn_code": "19059090",
        "gst_rate": 18,
        "description": "Traditional unniyappam snack",
        "confidence": 0.86,
        "category": "kerala_food",
    },
    "TAPIOCA CHIPS": {
        "search_terms": ["cassava chips", "tapioca snack"],
        "hsn_code": "20081940",
        "gst_rate": 12,
        "description": "Tapioca chips",
        "confidence": 0.89,
        "category": "kerala_food",
    },
    "KAPPA CHIPS": {
        "search_terms": ["cassava chips", "tapioca snack"],
        "hsn_code": "20081940",
        "gst_rate": 12,
        "description": "Kappa chips",
        "confidence": 0.89,
        "category": "kerala_food",
    },
    "TAPIOCA": {
        "search_terms": ["cassava root", "tapioca fresh", "kappa"],
        "hsn_code": "07141090",
        "gst_rate": 0,
        "description": "Fresh tapioca root",
        "confidence": 0.85,
        "category": "kerala_food",
    },
    "KAPPA": {
        "search_terms": ["cassava root", "tapioca fresh", "kappa"],
        "hsn_code": "07141090",
        "gst_rate": 0,
        "description": "Fresh tapioca root",
        "confidence": 0.85,
        "category": "kerala_food",
    },
    "KOZHUVA": {
        "search_terms": ["anchovy fish", "small dried fish"],
        "hsn_code": "03083020",
        "gst_rate": 5,
        "description": "Anchovy fish",
        "confidence": 0.87,
        "category": "kerala_seafood",
    },
    "KALLUMAKKAYA": {
        "search_terms": ["mussels", "shellfish"],
        "hsn_code": "03079100",
        "gst_rate": 5,
        "description": "Mussels shellfish",
        "confidence": 0.87,
        "category": "kerala_seafood",
    },
    "NJANDU": {
        "search_terms": ["crab", "mud crab"],
        "hsn_code": "03062900",
        "gst_rate": 5,
        "description": "Crab seafood",
        "confidence": 0.87,
        "category": "kerala_seafood",
    },
    "KARIMEEN": {
        "search_terms": ["pearl spot fish"],
        "hsn_code": "03028990",
        "gst_rate": 5,
        "description": "Karimeen pearl spot fish",
        "confidence": 0.87,
        "category": "kerala_seafood",
    },
    "SAMBAR PODI": {
        "search_terms": ["sambar powder spice mix", "sambar masala"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Sambar masala powder",
        "confidence": 0.86,
        "category": "kerala_spice",
    },
    "SAMBAR MASALA": {
        "search_terms": ["sambar powder spice mix", "sambar masala"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Sambar masala powder",
        "confidence": 0.86,
        "category": "kerala_spice",
    },
    "RASAM PODI": {
        "search_terms": ["rasam spice mix", "rasam powder"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Rasam spice powder",
        "confidence": 0.86,
        "category": "kerala_spice",
    },
    "RASAM POWDER": {
        "search_terms": ["rasam spice mix", "rasam powder"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Rasam spice powder",
        "confidence": 0.86,
        "category": "kerala_spice",
    },
    "THORAN": {
        "search_terms": ["stir fry vegetable mix", "thoran masala"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Thoran masala mix",
        "confidence": 0.82,
        "category": "kerala_spice",
    },
    "PATHIMUGHAM": {
        "search_terms": ["indian sarsaparilla", "hemidesmus", "pathimugham"],
        "hsn_code": "12119099",
        "gst_rate": 5,
        "description": "Indian sarsaparilla herb",
        "confidence": 0.9,
        "category": "kerala_herbal",
    },
    "KITCHEN TR": {
        "search_terms": ["kitchen treasure spice", "kitchen treasure masala"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Kitchen Treasure spice or masala",
        "confidence": 0.82,
        "category": "kerala_brand",
    },
    "KITCHEN TR.CHILLI PDR": {
        "search_terms": ["kitchen treasure chilli powder", "chilli powder"],
        "hsn_code": "09042211",
        "gst_rate": 5,
        "description": "Kitchen Treasure chilli powder",
        "confidence": 0.91,
        "category": "kerala_brand",
    },
    "KITCHEN TR.CHILLI POWDER": {
        "search_terms": ["kitchen treasure chilli powder", "chilli powder"],
        "hsn_code": "09042211",
        "gst_rate": 5,
        "description": "Kitchen Treasure chilli powder",
        "confidence": 0.91,
        "category": "kerala_brand",
    },
    "KITCHEN TR.CHICKEN MASALA": {
        "search_terms": ["kitchen treasure chicken masala", "chicken masala"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Kitchen Treasure chicken masala",
        "confidence": 0.89,
        "category": "kerala_brand",
    },
    "KITCHEN TR.RASAM PDR": {
        "search_terms": ["kitchen treasure rasam powder", "rasam powder"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Kitchen Treasure rasam powder",
        "confidence": 0.89,
        "category": "kerala_brand",
    },
    "BRAHMINS": {
        "search_terms": ["brahmins kerala spice", "brahmins masala"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Brahmins Kerala masala",
        "confidence": 0.8,
        "category": "kerala_brand",
    },
    "EASTERN MASALA": {
        "search_terms": ["eastern spice blend", "eastern masala"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Eastern spice blend",
        "confidence": 0.86,
        "category": "kerala_brand",
    },
    "EASTERN TURMERIC": {
        "search_terms": ["eastern turmeric powder", "turmeric powder"],
        "hsn_code": "09103030",
        "gst_rate": 5,
        "description": "Eastern turmeric powder",
        "confidence": 0.91,
        "category": "kerala_brand",
    },
    "EASTERN CORIANDER": {
        "search_terms": ["eastern coriander powder", "coriander powder"],
        "hsn_code": "09092200",
        "gst_rate": 5,
        "description": "Eastern coriander powder",
        "confidence": 0.91,
        "category": "kerala_brand",
    },
    "PAVITHRAM SESAME": {
        "search_terms": ["pavithram gingelly sesame oil", "sesame oil"],
        "hsn_code": "15155091",
        "gst_rate": 5,
        "description": "Pavithram sesame oil",
        "confidence": 0.9,
        "category": "kerala_brand",
    },
    "PAVITHRAM OIL": {
        "search_terms": ["pavithram edible oil", "sesame oil"],
        "hsn_code": "15155091",
        "gst_rate": 5,
        "description": "Pavithram edible oil",
        "confidence": 0.86,
        "category": "kerala_brand",
    },
    "IDHAYAM SESAME": {
        "search_terms": ["idhayam gingelly oil", "sesame oil"],
        "hsn_code": "15155091",
        "gst_rate": 5,
        "description": "Idhayam gingelly oil",
        "confidence": 0.9,
        "category": "kerala_brand",
    },
    "OM SHANTHI PUJA OIL": {
        "search_terms": ["om shanthi jasmine puja oil", "lamp oil"],
        "hsn_code": "15180040",
        "gst_rate": 5,
        "description": "Om Shanthi puja oil",
        "confidence": 0.91,
        "category": "kerala_brand",
    },
    "PUJA OIL": {
        "search_terms": ["lamp oil", "sesame puja oil", "pooja oil"],
        "hsn_code": "15180040",
        "gst_rate": 5,
        "description": "Puja lamp oil",
        "confidence": 0.86,
        "category": "kerala_brand",
    },
    "POOJA OIL": {
        "search_terms": ["lamp oil", "sesame puja oil", "puja oil"],
        "hsn_code": "15180040",
        "gst_rate": 5,
        "description": "Pooja lamp oil",
        "confidence": 0.86,
        "category": "kerala_brand",
    },
    "MILMA GHEE": {
        "search_terms": ["milma kerala cooperative ghee", "ghee"],
        "hsn_code": "04059020",
        "gst_rate": 5,
        "description": "Milma ghee",
        "confidence": 0.91,
        "category": "kerala_brand",
    },
    "MILMA MILK": {
        "search_terms": ["milma pasteurised milk", "milk"],
        "hsn_code": "04011000",
        "gst_rate": 0,
        "description": "Milma milk",
        "confidence": 0.9,
        "category": "kerala_brand",
    },
    "AACHI MASALA": {
        "search_terms": ["aachi spice blend", "masala powder"],
        "hsn_code": "09109100",
        "gst_rate": 5,
        "description": "Aachi masala blend",
        "confidence": 0.84,
        "category": "kerala_brand",
    },
    "DOUBLE HORSE": {
        "search_terms": ["double horse kerala flour products", "rice flour"],
        "hsn_code": "11029090",
        "gst_rate": 5,
        "description": "Double Horse flour products",
        "confidence": 0.8,
        "category": "kerala_brand",
    },
    "ELITE RICE": {
        "search_terms": ["elite rice flour kerala", "rice flour"],
        "hsn_code": "11029000",
        "gst_rate": 5,
        "description": "Elite rice flour",
        "confidence": 0.88,
        "category": "kerala_brand",
    },
    "ELITE PUTTUPODI": {
        "search_terms": ["elite rice flour kerala", "puttu flour"],
        "hsn_code": "11029000",
        "gst_rate": 5,
        "description": "Elite puttupodi",
        "confidence": 0.88,
        "category": "kerala_brand",
    },
    "AJMI PUTTUPODI": {
        "search_terms": ["ajmi steam puttu flour", "puttu flour"],
        "hsn_code": "11023000",
        "gst_rate": 5,
        "description": "Ajmi puttupodi",
        "confidence": 0.91,
        "category": "kerala_brand",
    },
    "BODHINI APPAM": {
        "search_terms": ["bodhini appam podi", "appam flour"],
        "hsn_code": "11029090",
        "gst_rate": 5,
        "description": "Bodhini appam flour",
        "confidence": 0.9,
        "category": "kerala_brand",
    },
    "CB MATTA RICE": {
        "search_terms": ["cb brand matta broken rice", "matta rice"],
        "hsn_code": "10064000",
        "gst_rate": 5,
        "description": "CB matta broken rice",
        "confidence": 0.9,
        "category": "kerala_brand",
    },
    "MANJAL PODI": {
        "search_terms": ["turmeric powder haldi", "manjal podi"],
        "hsn_code": "09103010",
        "gst_rate": 5,
        "description": "Turmeric powder manjal podi",
        "confidence": 0.91,
        "category": "kerala_spice",
    },
    "MULAKU PODI": {
        "search_terms": ["red chilli powder", "mulaku podi"],
        "hsn_code": "09042210",
        "gst_rate": 5,
        "description": "Chilli powder mulaku podi",
        "confidence": 0.91,
        "category": "kerala_spice",
    },
    "VELICHENNA": {
        "search_terms": ["coconut oil edible", "velichenna"],
        "hsn_code": "15131190",
        "gst_rate": 5,
        "description": "Coconut oil velichenna",
        "confidence": 0.9,
        "category": "kerala_food",
    },
    "KAAYAM": {
        "search_terms": ["asafoetida hing", "kaayam"],
        "hsn_code": "13019032",
        "gst_rate": 5,
        "description": "Asafoetida kaayam",
        "confidence": 0.9,
        "category": "kerala_spice",
    },
    "PUTTU PODI": {
        "search_terms": ["puttu rice flour", "puttu podi"],
        "hsn_code": "11023000",
        "gst_rate": 5,
        "description": "Puttu podi rice flour",
        "confidence": 0.91,
        "category": "kerala_food",
    },
    "PUZHUKKALARI": {
        "search_terms": ["parboiled rice kerala", "puzhukkalari"],
        "hsn_code": "10063020",
        "gst_rate": 5,
        "description": "Parboiled rice puzhukkalari",
        "confidence": 0.9,
        "category": "kerala_food",
    },
    "THUVARA PARIPPU": {
        "search_terms": ["toor dal pigeon pea", "thuvara parippu"],
        "hsn_code": "07136000",
        "gst_rate": 5,
        "description": "Thuvara parippu toor dal",
        "confidence": 0.9,
        "category": "kerala_food",
    },
    "KADALA MAVU": {
        "search_terms": ["besan chickpea flour", "kadala mavu"],
        "hsn_code": "11061090",
        "gst_rate": 5,
        "description": "Kadala mavu besan",
        "confidence": 0.9,
        "category": "kerala_food",
    },
    "NENDRAN CHIPS": {
        "search_terms": ["banana chips plantain", "nendran chips"],
        "hsn_code": "20081990",
        "gst_rate": 12,
        "description": "Nendran banana chips",
        "confidence": 0.89,
        "category": "kerala_food",
    },
    "NADAN ARI": {
        "search_terms": ["nadan rice traditional local", "nadan ari"],
        "hsn_code": "10063090",
        "gst_rate": 5,
        "description": "Nadan traditional rice",
        "confidence": 0.9,
        "category": "kerala_food",
    },
    "INJI PULI": {
        "search_terms": ["ginger tamarind pickle inji puli"],
        "hsn_code": "20019000",
        "gst_rate": 12,
        "description": "Inji puli ginger tamarind pickle",
        "confidence": 0.91,
        "category": "kerala_food",
    },
    "IDLY APPAM PODI": {
        "search_terms": ["idly appam podi rice flour", "idiappam flour"],
        "hsn_code": "11029090",
        "gst_rate": 5,
        "description": "Idly appam podi",
        "confidence": 0.9,
        "category": "kerala_food",
    },
    "KADALA": {
        "search_terms": ["black chana chickpea kadala"],
        "hsn_code": "07132090",
        "gst_rate": 5,
        "description": "Kadala black chickpea",
        "confidence": 0.88,
        "category": "kerala_food",
    },
}

# Corpus supplies vocabulary; curated map wins on same-key conflict (compliance policy).
from app.services.kerala_corpus_maps import corpus_derived_alias_map  # noqa: E402
from app.services.kerala_search_policy import merge_alias_maps  # noqa: E402

KERALA_ALIAS_MAP = merge_alias_maps(CURATED_KERALA_ALIAS_MAP, corpus_derived_alias_map())
