from __future__ import annotations

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def generate_gst_pdf(
    report_data: list[dict],
    branch_name: str,
    branch_gstin: str,
    period: str,
) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4)
    styles = getSampleStyleSheet()
    elements = []
    elements.append(Paragraph("GST Classification Report", styles["Title"]))
    elements.append(Paragraph(f"Branch: {branch_name} | GSTIN: {branch_gstin}", styles["Normal"]))
    elements.append(Paragraph(f"Period: {period}", styles["Normal"]))
    elements.append(Spacer(1, 12))

    table_data = [["HSN Code", "Description", "GST Rate (%)", "Count"]]
    for row in report_data:
        table_data.append(
            [
                row["hsn_code"],
                str(row.get("description", ""))[:60],
                str(row["gst_rate"]),
                str(row["transaction_count"]),
            ]
        )
    total = sum(int(r["transaction_count"]) for r in report_data)
    table_data.append(["TOTAL", "", "", str(total)])

    table = Table(table_data, colWidths=[80, 240, 80, 60])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a56db")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -2), [colors.white, colors.HexColor("#f3f4f6")]),
                ("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold"),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#d1d5db")),
            ]
        )
    )
    elements.append(table)
    elements.append(Spacer(1, 20))
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    elements.append(
        Paragraph(
            f"Generated by HSN Classifier - {ts}. For official filing, verify with GSTIN portal.",
            styles["Normal"],
        )
    )
    doc.build(elements)
    buffer.seek(0)
    return buffer.read()
