from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO

def generate_gst_pdf(report_data: list, branch, period) -> bytes:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4)
    styles = getSampleStyleSheet()
    elems = [
        Paragraph(f"GST Compliance Report - {getattr(branch, 'name', 'Branch')}", styles["Heading2"]),
        Paragraph(f"GSTIN: {getattr(branch, 'gstin', '-')}", styles["Normal"]),
        Paragraph(f"Period: {period}", styles["Normal"]),
        Spacer(1, 12),
    ]
    table_data = [["HSN Code", "Description", "GST Rate (%)", "Count"]]
    for row in report_data:
        table_data.append([row.get("hsn_code"), row.get("description"), row.get("gst_rate"), row.get("transaction_count")])
    table = Table(table_data, repeatRows=1)
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ]
        )
    )
    elems.append(table)
    elems.append(Spacer(1, 12))
    elems.append(
        Paragraph(
            f"Generated by HSN Classifier - {datetime.now(timezone.utc).isoformat()}. For official filing, verify with GSTIN portal.",
            styles["Italic"],
        )
    )
    doc.build(elems)
    return buf.getvalue()
